config/routes.rb
Rails.application.routes.draw do

    resources :anons do

        resources :comments, module: :inventories
    end

    resources :inventories do

        resources :comments, module: :inventories
    end

    resources :forums do

        resources :comments, module: :forums
    end

    resources :jobs do

        resources :comments, module: :jobs
    end

    resources :events do

        resources :comments, module: :events
    end

    devise_for :users

    get 'users/:id' => 'users#show', as: :user

    resources :homepages

    root 'homepages#index'

    get 'anon' => 'anons#index'

    get 'jobs' => 'job_lists#index'

    get 'categories' => 'categories#index'

    get 'events' => 'events#index'

    get 'forum' => 'forums#index'

end

app/models/forum.rb
class Forum < ActiveRecord::Base
    searchkick

  belongs_to :user

  has_many :comments, as: :commentable

end

app/controllers/forums/comments_controller.rb
class Forums::CommentsController < CommentsController
  before_action :set_commentable

  private

    def set_commentable
        @commentable = Forum.find(params[:forum_id])
    end
end

app/controllers/forums_controller.rb
class ForumsController < ApplicationController
  before_action :set_forum, only: [:show, :edit, :update, :destroy]
      before_filter :authenticate_user!


    def index
    @forums = Forum.all
  end

  # GET /forums/1
  # GET /forums/1.json
  def show
  end

  # GET /forums/new
  def new
    @forum = Forum.new
  end

  # GET /forums/1/edit
  def edit
  end

  # POST /forums
  # POST /forums.json
  def create
    @forum = Forum.new(forum_params)

    respond_to do |format|
      if @forum.save
        format.html { redirect_to @forum, notice: 'Forum was successfully created.' }
        format.json { render :show, status: :created, location: @forum }
      else
        format.html { render :new }
        format.json { render json: @forum.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /forums/1
  # PATCH/PUT /forums/1.json
  def update
    respond_to do |format|
      if @forum.update(forum_params)
        format.html { redirect_to @forum, notice: 'Forum was successfully updated.' }
        format.json { render :show, status: :ok, location: @forum }
      else
        format.html { render :edit }
        format.json { render json: @forum.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /forums/1
  # DELETE /forums/1.json
  def destroy
    @forum.destroy
    respond_to do |format|
      format.html { redirect_to forums_url, notice: 'Forum was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_forum
      @forum = Forum.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def forum_params
      params.require(:forum).permit(:title, :body, :user_id)
    end
end

app/helpers/forums_helper.rb
module ForumsHelper
end

app/views/forums/_form.html.erb
<%= form_for(@forum) do |f| %>
  <% if @forum.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@forum.errors.count, "error") %> prohibited this forum from being saved:</h2>

      <ul>
      <% @forum.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title, class: "form-control" %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body, class: "form-control" %>
  </div>
  <div class="form-group cant-see-me">
  <%= f.number_field :user_id, value: current_user.id %>
</div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/forums/edit.html.erb
<h1>Editing Forum</h1>

<%= render 'form' %>

<%= link_to 'Show', @forum %>
<%= link_to 'Back', forums_path %>
<%= link_to 'Destroy', @forum, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>

app/views/forums/index.html.erb
<p id="notice"><%= notice %></p>
  <div class="pull-right">
    <%= link_to "Create a new thread!", new_forum_path, class: "btn btn-success" %>
  </div>

<div class="well home-well">
<div class="row">
<div class="col-md-6-centered">
<div class="center">
<h1 class="page-header">Forums</h1>

<% @forums.each do |forum| %>
<h3><%= link_to forum.title, forum %></h3>
        <% end %>
       </div>
     </div>
     </div>
     </div>
<br>
<%= link_to 'Home', root_path, class: "btn btn-info" %>

app/views/forums/new.html.erb
<h1>New Forum</h1>

<%= render 'form' %>

<%= link_to 'Back', forums_path %>

app/views/forums/show.html.erb
<p id="notice"><%= notice %></p>
<div class="well home-well">
<div class="row">
<div class="col-md-6-centered">
<div class="center">
<h1><%= @forum.title %></h1>
<p class="text-muted">Created by <%= @forum.user.username %></p>
<%= @forum.body %>

<br>
<br>
<%= link_to 'Back', forums_path, class: "btn btn-success" %>
<% if current_user.id == @forum.user.id %>
<%= link_to 'Edit', edit_forum_path(@forum), class: "btn btn-warning" %>
<% end %>
  </div>
     </div>
     </div>
     </div>
<br>

<%= render partial: "comments/comments", locals: {commentable: @forum} %>

<%= render partial: "comments/form", locals: {commentable: @forum} %>