config/routes.rb
Rails.application.routes.draw do

    resources :anons do

        resources :comments, module: :inventories
    end

    resources :inventories do

        resources :comments, module: :inventories
    end

    resources :forums do

        resources :comments, module: :forums
    end

    resources :jobs do

        resources :comments, module: :jobs
    end

    resources :events do

        resources :comments, module: :events
    end

    devise_for :users

    get 'users/:id' => 'users#show', as: :user

    resources :homepages

    root 'homepages#index'

    get 'anon' => 'anons#index'

    get 'jobs' => 'job_lists#index'

    get 'categories' => 'categories#index'

    get 'events' => 'events#index'

    get 'forum' => 'forums#index'

end

app/models/job.rb
class Job < ActiveRecord::Base

    searchkick

  belongs_to :user

    has_many :comments, as: :commentable

end

app/controllers/jobs/comments_controller.rb
class Jobs::CommentsController < CommentsController
  before_action :set_commentable

  private

    def set_commentable
        @commentable = Job.find(params[:job_id])
    end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :set_job, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!

  def search
    if params[:search].present?
        @jobs = Job.search(params[:search])
    else
        @jobs = Job.all
    end
  end

  def index
    @jobs = Job.all
  end

  # GET /jobs/1
  # GET /jobs/1.json
  def show
  end

  # GET /jobs/new
  def new
    @job = Job.new
  end

  # GET /jobs/1/edit
  def edit
  end

  # POST /jobs
  # POST /jobs.json
  def create
    @job = Job.new(job_params)

    respond_to do |format|
      if @job.save
        format.html { redirect_to @job, notice: 'Job was successfully created.' }
        format.json { render :show, status: :created, location: @job }
      else
        format.html { render :new }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /jobs/1
  # PATCH/PUT /jobs/1.json
  def update
    respond_to do |format|
      if @job.update(job_params)
        format.html { redirect_to @job, notice: 'Job was successfully updated.' }
        format.json { render :show, status: :ok, location: @job }
      else
        format.html { render :edit }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /jobs/1
  # DELETE /jobs/1.json
  def destroy
    @job.destroy
    respond_to do |format|
      format.html { redirect_to jobs_url, notice: 'Job was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_job
      @job = Job.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def job_params
      params.require(:job).permit(:title, :description, :phone, :email, :user_id)
    end
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/jobs/_form.html.erb
<%= form_for(@job) do |f| %>
  <% if @job.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@job.errors.count, "error") %> prohibited this job from being saved:</h2>

      <ul>
      <% @job.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title, class: "form-control" %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description, class: "form-control" %>
  </div>
  <div class="field">
    <%= f.label :phone %><br>
    <%= f.number_field :phone, class: "form-control" %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_area :email, class: "form-control" %>
  </div>
    <div class="form-group cant-see-me">
      <%= f.number_field :user_id, value: current_user.id %>
    </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/jobs/edit.html.erb
<h1>Editing Job</h1>

<%= render 'form' %>

<%= link_to 'Show', @job %> |
<%= link_to 'Back', jobs_path %>
<%= link_to 'Destroy', @job, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>

app/views/jobs/index.html.erb
<p id="notice"><%= notice %></p>

  <div class="pull-right">
<%= link_to 'List a new job!', new_job_path, class: "btn btn-success" %>
  </div>
<div class="well home-well">
<div class="row">
<div class="col-md-6-centered">
<div class="center">
<h1 class="page-header">Posted Jobs</h1>
      <% @jobs.each do |job| %>
  <h3><%= link_to job.title, job %></h3>
    <% end %>
<br>
</div>
</div>
</div>
</div>
    <%= link_to 'Home', root_path, class: "btn btn-info" %>

app/views/jobs/new.html.erb
<h1>New Job</h1>

<%= render 'form' %>

<%= link_to 'Back', jobs_path %>

app/views/jobs/show.html.erb
<p id="notice"><%= notice %></p>
<div class="container">
    <div class="well home-well">
    <h1> <%= @job.title %></h1>
    <p class="text-muted">This job was posted by <%= @job.user.name %> <%= local_time_ago @job.created_at %></p>

 <h3><strong>Description:</strong></h3>
 <h3><%= @job.description %></h3>
<br>
    <h4><strong>Contact Info: </strong><%= @job.phone %> | <%= @job.email %></h4>
</div>

  <% if current_user.id == @job.user.id %>

    <div class="panel-footer">
<%= link_to 'Edit', edit_job_path(@job), class: "btn btn-warning" %>
            <% end %>
</div>
</div>
        <%= render partial: "comments/comments", locals: {commentable: @job} %>

<%= render partial: "comments/form", locals: {commentable: @job} %>
<br>


        <%= link_to 'Back', jobs_path, class: "btn btn-success" %>