config/routes.rb
Rails.application.routes.draw do

    resources :anons do

        resources :comments, module: :inventories
    end

    resources :inventories do

        resources :comments, module: :inventories
    end

    resources :forums do

        resources :comments, module: :forums
    end

    resources :jobs do

        resources :comments, module: :jobs
    end

    resources :events do

        resources :comments, module: :events
    end

    devise_for :users

    get 'users/:id' => 'users#show', as: :user

    resources :homepages

    root 'homepages#index'

    get 'anon' => 'anons#index'

    get 'jobs' => 'job_lists#index'

    get 'categories' => 'categories#index'

    get 'events' => 'events#index'

    get 'forum' => 'forums#index'

end

app/models/anon.rb
class Anon < ActiveRecord::Base

    searchkick

  belongs_to :user

  has_many :comments, as: :commentable

end

app/models/category.rb
class Category < ActiveRecord::Base
    has_many :inventories
    
end

app/models/comment.rb
class Comment < ActiveRecord::Base

    belongs_to :commentable, polymorphic: true

    belongs_to :user
end

app/models/event.rb
class Event < ActiveRecord::Base
    searchkick

  belongs_to :user

    attachment :event_image

    has_many :comments, as: :commentable
end

app/models/examp.rb
class Examp < ActiveRecord::Base
end

app/models/forum.rb
class Forum < ActiveRecord::Base
    searchkick

  belongs_to :user

  has_many :comments, as: :commentable

end

app/models/homepage.rb
class Homepage < ActiveRecord::Base
end

app/models/inventory.rb
class Inventory < ActiveRecord::Base

  belongs_to :user

    attachment :item_image

  has_many :comments, as: :commentable

end

app/models/job.rb
class Job < ActiveRecord::Base

    searchkick

  belongs_to :user

    has_many :comments, as: :commentable

end

app/models/user.rb
class User < ActiveRecord::Base

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

         validates :email, presence: true, uniqueness: true

         validates :username, presence: true, uniqueness: true

         validates :name, presence: true

#######Everything above this comment pertains to devise.
  has_many :jobs

  has_many :events

  has_many :forums

  has_many :comments

  has_many :inventories

  attachment :profile_image


end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :set_job, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!

  def search
    if params[:search].present?
        @jobs = Job.search(params[:search])
    else
        @jobs = Job.all
    end
  end

  def index
    @jobs = Job.all
  end

  # GET /jobs/1
  # GET /jobs/1.json
  def show
  end

  # GET /jobs/new
  def new
    @job = Job.new
  end

  # GET /jobs/1/edit
  def edit
  end

  # POST /jobs
  # POST /jobs.json
  def create
    @job = Job.new(job_params)

    respond_to do |format|
      if @job.save
        format.html { redirect_to @job, notice: 'Job was successfully created.' }
        format.json { render :show, status: :created, location: @job }
      else
        format.html { render :new }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /jobs/1
  # PATCH/PUT /jobs/1.json
  def update
    respond_to do |format|
      if @job.update(job_params)
        format.html { redirect_to @job, notice: 'Job was successfully updated.' }
        format.json { render :show, status: :ok, location: @job }
      else
        format.html { render :edit }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /jobs/1
  # DELETE /jobs/1.json
  def destroy
    @job.destroy
    respond_to do |format|
      format.html { redirect_to jobs_url, notice: 'Job was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_job
      @job = Job.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def job_params
      params.require(:job).permit(:title, :description, :phone, :email, :user_id)
    end
end

app/helpers/anons_helper.rb
module AnonsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/examps_helper.rb
module ExampsHelper
end

app/helpers/forums_helper.rb
module ForumsHelper
end

app/helpers/homepages_helper.rb
module HomepagesHelper
end

app/helpers/inventories_helper.rb
module InventoriesHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/layouts/_navbar.html.erb
<!--This is the navbar-->
<% if user_signed_in? %>

<nav class="navbar navbar-default">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
        <div class="navbar-brand"><%= link_to "ServiceU", root_path %></div>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Buy/Sell <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
            <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
            <li><a href="#">Something else here</a></li>
            <li class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
          <li><%= link_to "Events", events_path %></li>
            <li><%= link_to "Jobs", jobs_path %></li>
            <li><%= link_to "Forum", forums_path %></li>
            <form class="navbar-form navbar-left" role="search">
            <div class="form-group">
              <input type="text" class="form-control" placeholder="Search">
            </div>
            <button type="submit" class="btn btn-default">Submit</button>
          </form>
      </ul>

      <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "Anonymous Forum", anons_path %></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><%= image_tag attachment_url(current_user, :profile_image, :fill, 50, 50, format: "jpg") %>
            <span class="caret"></span></a>
            <ul class="dropdown-menu" role="menu">
              <li><%= link_to "Your Profile", edit_user_registration_path %></li>
              <li class="divider"></li>
        <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
       <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
<% else %>
    <nav class="navbar navbar-default">
    <div class="container">
        <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
             <span class="icon-bar"></span>
            </button>
                    <div class="navbar-brand"><%= link_to "ServiceU", root_path %></div>

  <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "Sign In", new_user_session_path %></li>
            <li><%= link_to "Sign Up", new_user_registration_path %></li>
            <li><%= link_to "Forgot Password", new_user_session_path %></li>
            </ul>
        </div>
        </div>
    </nav>
    <% end %>

app/views/layouts/application.html.erb
<!--In order to keep this page better organized, you'll find that I rendered the navbar from layouts/navbar-->
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
   <meta http-equiv="X-UA-Compatible" content="IE=edge">
   <meta name="viewport" content="width=device-width, initial-scale=1">
 <title>Serviceu</title>
 <%= stylesheet_link_tag "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css"%>
 <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
 <%= javascript_include_tag "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js" %>
 <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
 <%= csrf_meta_tags %>

 <link href='http://fonts.googleapis.com/css?family=Trade+Winds|Fredericka+the+Great|Rum+Raisin|Ruslan+Display|Walter+Turncoat|Monoton|Orbitron|Architects+Daughter|Kaushan+Script|Rock+Salt|Slackey|Freckle+Face|Ranchers|Joti+One|Risque' rel='stylesheet' type='text/css'>
     <link href='http://fonts.googleapis.com/css?family=Orbitron' rel='stylesheet' type='text/css'>
    </head>
<body>
    <%= render 'layouts/navbar' %>
<div class="container">
<%= yield %>
</div>
</body>
</html>